name: codio-publish
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cleanup
        run: rm -rf .github README.md .git

      - name: Archive
        run: tar czf ../assignment.tar.gz . && mv ../assignment.tar.gz assignment.tar.gz

      - name: Upload artifactory
        uses: actions/upload-artifact@master
        with:
          name: assignment
          path: assignment.tar.gz
          retention-days: 2

  publish:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@master
        with:
          name: assignment

      - name: Log into Codio
        id: codio-login
        uses: codio/codio-auth-action@master
        with:
          client-id: ${{ secrets.CODIO_TEST1_CLIENT_ID }}
          secret-id: ${{ secrets.CODIO_TEST1_SECRET_ID }}
          domain: test1-codio.com

      - name: Publish to Codio
        uses: codio/codio-book-publish-action@master
        with:
          token: ${{ steps.codio-login.outputs.token }}
          book-id: 5777e7e3b2ce90d2325e923d981a0a06
          domain: test1-codio.com
          zip: ../data.zip
          changelog: ${{ github.event.head_commit.message }}

      - name: Update Codio Course
        uses: codio/codio-course-book-update-action@master
        with:
          token: ${{ steps.codio-login.outputs.token }}
          course-id: 5d2627e6b643887c072eea40
          book-id: 5777e7e3b2ce90d2325e923d981a0a06
          domain: test1-codio.com
