name: codio-publish
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cleanup
        run: rm -rf README.md .git

      - name: Publish to Codio
        uses: codio/codio-assignment-publish-action@updated-version-books
        with:
          client-id: ${{ secrets.CODIO_TEST1_CLIENT_ID }}
          secret-id: ${{ secrets.CODIO_TEST1_SECRET_ID }}
          dir: ./
          course-id: 5d2627e6b643887c072eea40
          changelog: ${{ github.event.head_commit.message }}
          yml: ./.github/yaml_map

